FROM mysql:5.7

LABEL  mantainer="Jounet" \
			descripton="sql" \
			version="1.0"

#VOLUME /mysql-data

# Add a database
ENV MYSQL_DATABASE Inventory

# 
RUN set -eux; \
			  apt-get update; \
			  apt-get install -y git;

# Copy Scripts SQL to Docker
RUN git clone https://github.com/iJou/actv3.git /myconfsql/
RUN cp -R /myconfsql/mysql/sqlscript/* /docker-entrypoint-initdb.d/
